name: impact
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  provider: ^4.0.5+1
  shared_preferences: ^0.5.7+1
  flutter_svg: ^0.17.4
  charts_flutter: ^0.9.0
  flutter_circular_chart: ^0.1.0
  flutter_launcher_icons: ^0.7.5
  flare_flutter: ^2.0.3
  image_sequence_animator: ^1.0.6
  nima: ^1.0.5
  jiffy: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    #  - images/a_dot_burr.jpeg
    #  - images/a_dot_ham.jpeg
    - assets/background.png
    - assets/impact.svg
    - assets/impact.gif
    - assets/impact.png
    - assets/impact-white.png
    - assets/background-large.jpg
    - assets/personal-info.png
    - assets/vehicle-info.png
    - assets/energy-info.png
    - assets/improve.png
    - assets/default-profile.png
    - assets/underground.png
    # - assets/sequence/
    # - assets/impact-2/
    # - assets/impact-21/
    # - assets/impact-2/impact-2.nma
    # - assets/impact-2/impact-20.png
    # - assets/impact-2/impact-21.png
    # - assets/impact-2/impact-22.png
    # - assets/impact-2/impact-23.png
    # - assets/impact-2/impact-24.png
    # - assets/impact-2/impact-25.png
    # - assets/impact-2/impact-26.png
    # - assets/impact-2/impact-27.png
    # - assets/impact-2/impact-28.png
    # - assets/impact-2/impact-29.png
    # - assets/impact-2/impact-210.png
    # - assets/impact-2/impact-211.png
    # - assets/impact-2/impact-212.png
    # - assets/impact-2/impact-213.png
    # - assets/impact-2/impact-214.png
    # - assets/impact-2/impact-215.png
    # - assets/impact-2/impact-216.png
    # - assets/impact-2/impact-217.png
    # - assets/impact-2/impact-218.png
    # - assets/impact-2/impact-219.png
    # - assets/impact-2/impact-220.png
    # - assets/impact-2/impact-221.png
    # - assets/impact-2/impact-222.png
    # - assets/impact-2/impact-223.png
    # - assets/impact-2/impact-224.png
    # - assets/impact-2/impact-225.png
    # - assets/impact-2/impact-226.png
    # - assets/impact-2/impact-227.png
    # - assets/impact-2/impact-228.png
    # - assets/impact-2/impact-229.png
    # - assets/impact-2/impact-230.png
    # - assets/impact-2/impact-231.png
    # - assets/impact-2/impact-232.png
    # - assets/impact-2/impact-233.png
    # - assets/impact-2/impact-234.png
    # - assets/impact-2/impact-235.png
    # - assets/impact-2/impact-236.png
    # - assets/impact-2/impact-237.png
    # - assets/impact-2/impact-238.png
    # - assets/impact-2/impact-239.png
    # - assets/impact-2/impact-240.png
    # - assets/impact-2/impact-241.png
    # - assets/impact-2/impact-242.png
    # - assets/impact-2/impact-243.png
    # - assets/impact-2/impact-244.png
    # - assets/impact-2/impact-245.png
    # - assets/impact-2/impact-246.png
    # - assets/impact-2/impact-247.png
    # - assets/impact-2/impact-248.png
    # - assets/impact-2/impact-249.png
    # - assets/impact-2/impact-250.png
    # - assets/impact-2/impact-251.png
    # - assets/impact-2/impact-252.png
    # - assets/impact-2/impact-253.png
    # - assets/impact-2/impact-254.png
    # - assets/impact-2/impact-255.png
    # - assets/impact-2/impact-256.png
    # - assets/impact-2/impact-257.png
    # - assets/impact-2/impact-258.png
    # - assets/impact-2/impact-259.png
    # - assets/impact-2/impact-260.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
