/// Flutter icons MyFlutterApp
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';

  static const IconData logo = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData electricity =
      const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData gas = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData improve = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData insights =
      const IconData(0xe806, fontFamily: _kFontFam);
}
